version: '3.7'
services:
  db:
    image: mongo:3.6
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/mongodb
    restart: always
    expose:
      - '27017'
    networks:
      - server

  backend:
    image: snapfork/snapforkbackend:latest
    container_name: 'app_backend'
    env_file:
      - .env
    volumes:
      - /app/snapfork/public:/public
    expose:
      - '3000'
    depends_on:
      - db
    networks:
      - server

  frontend:
    image: snapfork/snapforkfrontend:latest
    container_name: 'app_frontend'
    volumes:
      - /app/snapfork/nginx/sites-available:/etc/nginx/conf.d
      - /app/snapfork/nginx/log:/var/log/nginx
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - server

networks:
  server:
    name: server
