version: '3.7'
services:
  db:
    image: mongo:3.6
    container_name: mongobd
    volumes:
      - ./mongo-data:/data/mongodb
    restart: always
    ports:
      - '27017:27017'
    networks:
      - backend

  server:
    image: snapfork/snapforkbackend:latest
    container_name: 'api_backend'
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    name: app_backend
