version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: "node-12.19.0.dockerfile"
    container_name: "app_node"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: "mariadb:10.5.6"
    container_name: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    networks:
      - backend

networks:
  backend:
    name: app_backend